package com.comphenix.protocol.reflect;

/**
 * Invoked when a field is inaccessible due to security limitations, or when it simply doesn't exist.
 * 
 * @author Kristian
 */
public class FieldAccessException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 1911011681494034617L;

	public FieldAccessException() {
		super();
	}
	
	public FieldAccessException(String message, Throwable cause) {
		super(message, cause);
	}

	public FieldAccessException(String message) {
		super(message);
	}

	public FieldAccessException(Throwable cause) {
		super(cause);
	}
	
	public static FieldAccessException fromFormat(String message, Object... params) {
		return new FieldAccessException(String.format(message, params));
	}
}
